plugins {
    id 'java'
    id 'maven-publish'
    id 'net.fabricmc.fabric-loom' version '1.17.17'
}

version = project.mod_version
group = project.mod_group_id

base {
    archivesName = project.mod_id + "-fabric"
}

repositories {
    maven { url = 'https://maven.fabricmc.net/' }
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "seeleaderzombie" {
            sourceSet sourceSets.main
        }
    }
}

fabricApi {
    configureDataGeneration()
}

dependencies {
    // Minecraft and Fabric Loader
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings loom.officialMojangMappings()
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric API
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
    withSourcesJar()
    withJavadocJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}"}
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }
    repositories {
        maven {
            url "file://${project.projectDir}/repo"
        }
    }
}
