license = "GNU GENERAL PUBLIC LICENSE"
modLoader = "javafml"
loaderVersion = "[4,)"

[[mods]]
modId = "seeleaderzombie"
version = "1.2"
displayName = "SeeLeaderZombie"
authors = ["roboticrobot"]
description = """A mod that shows you the leader zombie. Pretty scary!"""

[[dependencies."seeleaderzombie"]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.2,26.2.0)"
ordering = "NONE"
side = "BOTH"

[[dependencies."seeleaderzombie"]]
modId = "minecraft"
type = "required"
versionRange = "[26.1.2,26.2)"
ordering = "NONE"
side = "BOTH"
